/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Aurora (https://sketchfab.com/auroraplz)
license: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
source: https://sketchfab.com/3d-models/trees-and-foliage-c3423a86515444a2b323d422ac16e710
title: Trees and foliage
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { Group } from "three";
import { GroupProps } from "@react-three/fiber";

export type TTreeSource =
  | "pine_tree"
  | "leaf"
  | "pumpkin"
  | "mushroom"
  | "birch_tree"
  | "god_tree";

export interface DynamicTreeProps extends GroupProps {
  treeSource: TTreeSource;
}

const SCALE_BASE_MAPPED: Record<DynamicTreeProps["treeSource"], number> = {
  pine_tree: 0.7,
  leaf: 2,
  pumpkin: 1.2,
  mushroom: 0.4,
  birch_tree: 1.2,
  god_tree: 0.745,
};

interface IGroupProps {
  group: any;
  props: any;
  nodes: any;
  materials: any;
}

function GodTree({ group, props, nodes, materials }: IGroupProps) {
  return (
    <group ref={group} dispose={null}>
      <mesh
        name="ground"
        position={props.position}
        scale={undefined}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <boxBufferGeometry attach="geometry" args={[4.75, 4.75, 0.2]} />
        <meshStandardMaterial attach="material" color="white" />
      </mesh>
      <group {...props} rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_3.geometry}
          material={materials.TreeB}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_2.geometry}
          material={materials.Ground}
        />
      </group>
    </group>
  );
}

function BirchTree({ group, props, nodes, materials }: IGroupProps) {
  return (
    <group ref={group} dispose={null}>
      <mesh
        name="ground"
        position={props.position}
        scale={undefined}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <boxBufferGeometry attach="geometry" args={[4.75, 4.75, 0.2]} />
        <meshStandardMaterial attach="material" color="white" />
        {/* <Edges /> */}
      </mesh>
      <group {...props} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.96, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube1_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.05, 4.97, 1.04]}
            rotation={[-0.2, 0.09, 0.34]}
            scale={[1.18, 0.9, 1.64]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube2_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.43, 2.88, 0.19]}
            rotation={[0, 0, 0.34]}
            scale={[0.96, 0.82, 1.13]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube3_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-1.33, 5.26, -1.17]}
            rotation={[0.25, -0.1, 0.23]}
            scale={[1.75, 0.97, 2.12]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube4_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-1.2, 5.62, -0.94]}
            rotation={[0.2, -0.48, 0.13]}
            scale={[1.92, 0.86, 0.98]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube5_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.37, 4.57, 1.55]}
            rotation={[0, -0.36, 0]}
            scale={[0.82, 0.82, 1.05]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube6_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.37, 5.94, -0.14]}
            rotation={[0.18, -0.05, 0]}
            scale={[2.08, 1, 1.17]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube7_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[0.22, 4.15, -1.01]}
            rotation={[0.1, -0.85, 0.33]}
            scale={[1.13, 0.78, 1.13]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube8_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group position={[0.23, 5.25, -2.06]} scale={[1.57, 1.3, 1.12]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube9_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.35, 6.05, -1.57]}
            rotation={[0.2, -0.09, 0.07]}
            scale={[1.39, 1, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube10_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group position={[1.08, 5.45, 0.45]} scale={[2.65, 1.21, 1.66]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube11_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.59, 5.33, -0.01]}
            rotation={[0, 0.97, 0.37]}
            scale={[2.78, 1.01, 2.3]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube12_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group position={[1.39, 5.3, -0.96]} scale={[1.05, 1, 1.05]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube13_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group position={[1.78, 4.9, -0.43]} scale={[1.73, 1, 1.39]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube14_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[0.85, 6.07, -0.42]}
            rotation={[-0.37, 0, 0]}
            scale={[1, 1.2, 1]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube15_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group position={[0, -0.36, -0.04]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pPlane1_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group
            position={[-0.1, -2.57, -0.41]}
            rotation={[0, -1.2, 0]}
            scale={[1, 1, 0.92]}
          >
            <group
              position={[0.22, 3.32, -1.01]}
              rotation={[-0.49, 1, 0.61]}
              scale={[1.13, 0.78, 1.13]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pCube8_lambert1_0.geometry}
                material={materials.lambert1}
              />
            </group>
          </group>
          <group
            position={[-0.35, -3.23, -0.65]}
            rotation={[0, -0.84, -0.27]}
            scale={[1, 1, 0.74]}
          >
            <group
              position={[-0.43, 3.59, 1.45]}
              rotation={[0, -0.36, 0]}
              scale={[1.14, 0.95, 1.05]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pCube6_lambert1_0.geometry}
                material={materials.lambert1}
              />
            </group>
          </group>
          <group
            position={[-0.21, 0.63, -0.41]}
            rotation={[-0.13, -0.39, 1.47]}
            scale={[0.29, 0.35, 0.05]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pPlane2_lambert3_0.geometry}
              material={materials.lambert3}
            />
          </group>
          <group position={[-0.05, 0.89, 0.07]}>
            <group
              position={[-1.3, -0.41, -1.39]}
              rotation={[-0.19, -0.81, 1.44]}
              scale={[0.29, 0.35, 0.05]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pPlane2_pasted__lambert3_0.geometry}
                material={materials.pasted__lambert3}
              />
            </group>
          </group>
          <group position={[0, 0.96, 0]}>
            <group position={[-0.05, -0.08, 0.07]}>
              <group
                position={[-0.21, -0.4, -0.53]}
                rotation={[-0.13, -0.39, 1.47]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pPlane2_pasted__pasted__lambert3_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert3}
                />
              </group>
            </group>
          </group>
          <group position={[-1.1, 0.77, 0.62]} rotation={[0.5, -0.62, 0.28]}>
            <group
              position={[-0.21, -0.33, -0.41]}
              rotation={[-0.13, -0.39, 1.47]}
              scale={[0.29, 0.35, 0.05]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pPlane2_pasted__lambert4_0.geometry}
                material={materials.pasted__lambert4}
              />
            </group>
            <group position={[-0.05, -0.08, 0.07]}>
              <group
                position={[-0.21, -0.33, -0.41]}
                rotation={[-0.13, -0.39, 1.47]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pPlane2_pasted__pasted__lambert4_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert4}
                />
              </group>
            </group>
            <group position={[-0.05, -0.08, 0.07]}>
              <group
                position={[-0.21, -0.4, -0.53]}
                rotation={[-0.13, -0.39, 1.47]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes
                      .pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__lambert3_0
                      .geometry
                  }
                  material={materials.pasted__pasted__pasted__lambert3}
                />
              </group>
            </group>
          </group>
          <group position={[1.73, 0.72, -1.64]} rotation={[-0.33, 0.31, -0.07]}>
            <group position={[-1.1, -0.19, 0.62]} rotation={[0.5, -0.62, 0.28]}>
              <group
                position={[-0.21, -0.33, -0.41]}
                rotation={[-0.13, -0.39, 1.47]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pPlane2_pasted__pasted__lambert5_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert5}
                />
              </group>
              <group position={[-0.05, -0.08, 0.07]}>
                <group
                  position={[-0.21, -0.33, -0.41]}
                  rotation={[-0.13, -0.39, 1.47]}
                  scale={[0.29, 0.35, 0.05]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__lambert4_0
                        .geometry
                    }
                    material={materials.pasted__pasted__pasted__lambert4}
                  />
                </group>
              </group>
              <group position={[-0.05, -0.08, 0.07]}>
                <group
                  position={[-0.21, -0.4, -0.53]}
                  rotation={[-0.13, -0.39, 1.47]}
                  scale={[0.29, 0.35, 0.05]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__pasted__lambert3_0
                        .geometry
                    }
                    material={
                      materials.pasted__pasted__pasted__pasted__lambert3
                    }
                  />
                </group>
              </group>
            </group>
          </group>
          <group position={[0, 0.96, 0]}>
            <group
              position={[-1.22, -0.41, -1.34]}
              rotation={[-0.19, -0.81, 1.44]}
              scale={[0.29, 0.35, 0.05]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pPlane2_pasted__lambert5_0.geometry}
                material={materials.pasted__lambert5}
              />
            </group>
            <group position={[-0.05, -0.08, 0.07]}>
              <group
                position={[-0.21, -0.33, -0.41]}
                rotation={[-0.13, -0.39, 1.47]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pPlane2_pasted__pasted__lambert6_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert6}
                />
              </group>
            </group>
            <group position={[-0.05, -0.08, 0.07]}>
              <group
                position={[-1.19, -0.41, -1.5]}
                rotation={[-0.19, -0.81, 1.44]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes
                      .pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__lambert5_0
                      .geometry
                  }
                  material={materials.pasted__pasted__pasted__lambert5}
                />
              </group>
            </group>
          </group>
          <group position={[0.27, 0.82, 1.12]} rotation={[0.28, 0, -0.12]}>
            <group
              position={[-0.21, -0.33, -0.41]}
              rotation={[-0.13, -0.39, 1.47]}
              scale={[0.29, 0.35, 0.05]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pPlane2_pasted__lambert6_0.geometry}
                material={materials.pasted__lambert6}
              />
            </group>
            <group position={[-0.05, -0.08, 0.07]}>
              <group
                position={[-0.21, -0.4, -0.53]}
                rotation={[-0.13, -0.39, 1.47]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes
                      .pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__lambert6_0
                      .geometry
                  }
                  material={materials.pasted__pasted__pasted__lambert6}
                />
              </group>
            </group>
            <group position={[-0.05, -0.08, 0.07]}>
              <group
                position={[-0.21, -0.33, -0.41]}
                rotation={[-0.13, -0.39, 1.47]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes
                      .pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__lambert7_0
                      .geometry
                  }
                  material={materials.pasted__pasted__pasted__lambert7}
                />
              </group>
            </group>
          </group>
          <group position={[0.66, 0.84, 0.58]} rotation={[-2.89, 0.86, -3]}>
            <group position={[0.27, -0.14, 1.12]} rotation={[0.28, 0, -0.12]}>
              <group
                position={[-0.21, -0.33, -0.41]}
                rotation={[-0.13, -0.39, 1.47]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pPlane2_pasted__pasted__lambert7_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert7}
                />
              </group>
              <group position={[-0.05, -0.08, 0.07]}>
                <group
                  position={[-0.21, -0.4, -0.53]}
                  rotation={[-0.13, -0.39, 1.47]}
                  scale={[0.29, 0.35, 0.05]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__pasted__lambert6_0
                        .geometry
                    }
                    material={
                      materials.pasted__pasted__pasted__pasted__lambert6
                    }
                  />
                </group>
              </group>
              <group position={[-0.05, -0.08, 0.07]}>
                <group
                  position={[-0.21, -0.33, -0.41]}
                  rotation={[-0.13, -0.39, 1.47]}
                  scale={[0.29, 0.35, 0.05]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__pasted__lambert7_0
                        .geometry
                    }
                    material={
                      materials.pasted__pasted__pasted__pasted__lambert7
                    }
                  />
                </group>
              </group>
            </group>
          </group>
          <group position={[-1.29, 0.88, 0.3]} rotation={[0, 0.43, 0]}>
            <group position={[0.27, -0.14, 1.12]} rotation={[0.28, 0, -0.12]}>
              <group
                position={[-0.21, -0.33, -0.41]}
                rotation={[-0.13, -0.39, 1.47]}
                scale={[0.29, 0.35, 0.05]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pPlane2_pasted__pasted__lambert8_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert8}
                />
              </group>
              <group position={[-0.05, -0.08, 0.07]}>
                <group
                  position={[-0.21, -0.4, -0.53]}
                  rotation={[-0.13, -0.39, 1.47]}
                  scale={[0.29, 0.35, 0.05]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__pasted__lambert8_0
                        .geometry
                    }
                    material={
                      materials.pasted__pasted__pasted__pasted__lambert8
                    }
                  />
                </group>
              </group>
              <group position={[-0.05, -0.08, 0.07]}>
                <group
                  position={[-0.21, -0.33, -0.41]}
                  rotation={[-0.13, -0.39, 1.47]}
                  scale={[0.29, 0.35, 0.05]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pasted__pPlane2_pasted__pasted__pasted__pasted__lambert9_0
                        .geometry
                    }
                    material={
                      materials.pasted__pasted__pasted__pasted__lambert9
                    }
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            position={[-1.29, 0.31, -0.77]}
            rotation={[-0.07, 0.1, 0.05]}
            scale={[0.3, 0.94, 0.51]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube16_lambert4_0.geometry}
              material={materials.lambert4}
            />
          </group>
          <group
            position={[0.25, 0.9, 0.03]}
            rotation={[0.12, -0.06, 0]}
            scale={[0.89, 1, 1]}
          >
            <group
              position={[-1.29, -0.65, -0.77]}
              rotation={[-0.07, 0, 0.05]}
              scale={[0.3, 0.94, 0.51]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pCube16_pasted__lambert7_0.geometry}
                material={materials.pasted__lambert7}
              />
            </group>
          </group>
          <group
            position={[0.56, 0.96, -0.58]}
            rotation={[-0.14, 0, -0.12]}
            scale={[1, 1, 0.82]}
          >
            <group
              position={[0.25, -0.06, 0.03]}
              rotation={[0.12, -0.06, 0]}
              scale={[0.89, 1, 1]}
            >
              <group
                position={[-1.29, -0.65, -0.77]}
                rotation={[-0.08, 0.27, 0.05]}
                scale={[0.3, 0.94, 0.51]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pCube16_pasted__pasted__lambert9_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert9}
                />
              </group>
            </group>
          </group>
          <group
            position={[1.52, 1.05, -0.72]}
            rotation={[-0.08, 0, 0]}
            scale={[0.95, 1, 1]}
          >
            <group
              position={[-1.29, -0.65, -0.77]}
              rotation={[-0.07, 0, 0.05]}
              scale={[0.3, 0.94, 0.51]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pCube16_pasted__lambert8_0.geometry}
                material={materials.pasted__lambert8}
              />
            </group>
          </group>
          <group
            position={[1.53, 1.03, -1.07]}
            rotation={[-0.23, 0, 0]}
            scale={[0.84, 0.86, 0.82]}
          >
            <group
              position={[0.25, -0.06, 0.03]}
              rotation={[0.12, -0.06, 0]}
              scale={[0.89, 1, 1]}
            >
              <group
                position={[-1.29, -0.65, -0.77]}
                rotation={[-0.06, -0.23, 0.05]}
                scale={[0.3, 0.94, 0.51]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pCube16_pasted__pasted__lambert10_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert10}
                />
              </group>
            </group>
          </group>
          <group
            position={[-1.87, 0.83, 0.74]}
            rotation={[0.06, -0.18, 0.33]}
            scale={[0.75, 1, 1]}
          >
            <group
              position={[0.56, 0, -0.58]}
              rotation={[-0.14, 0, -0.12]}
              scale={[1, 1, 0.82]}
            >
              <group
                position={[0.25, -0.06, 0.03]}
                rotation={[0.12, -0.06, 0]}
                scale={[0.89, 1, 1]}
              >
                <group
                  position={[-1.29, -0.65, -0.77]}
                  rotation={[-0.07, 0, 0.05]}
                  scale={[0.3, 0.94, 0.51]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pCube16_pasted__pasted__pasted__lambert9_0
                        .geometry
                    }
                    material={materials.pasted__pasted__pasted__lambert9}
                  />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

function Mushroom({ group, props, nodes, materials }: IGroupProps) {
  return (
    <group ref={group} dispose={null}>
      <mesh
        name="ground"
        position={props.position}
        scale={undefined}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <boxBufferGeometry attach="geometry" args={[4.75, 4.75, 0.2]} />
        <meshStandardMaterial attach="material" color="white" />
      </mesh>
      <group
        {...props}
        position={[
          props.position[0],
          props.position[1] + 0.7,
          props.position[2],
        ]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.pSphere1_lambert2_0.geometry}
            material={materials.lambert2}
          />
        </group>
      </group>
    </group>
  );
}

function Pumpkin({ group, props, nodes, materials }: IGroupProps) {
  return (
    <group ref={group} dispose={null}>
      <mesh
        name="ground"
        position={props.position}
        scale={undefined}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <boxBufferGeometry attach="geometry" args={[4.75, 4.75, 0.2]} />
        <meshStandardMaterial attach="material" color="white" />
      </mesh>
      <group {...props} rotation={[-Math.PI / 2, 0, 0]}>
        <group
          rotation={[Math.PI / 2, (Math.PI / 2) * 2, 0]}
          position={[0.9, 0.5, 0]}
        >
          <group position={[0.6, 0.93, -0.15]} scale={[1, 0.84, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pSphere1_lambert8_0.geometry}
              material={materials.lambert8}
            />
          </group>
          <group position={[0.8, 0.16, -0.5]} scale={0.74}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube1_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group position={[1.58, 0.88, -1.03]}>
            <group
              position={[0.12, -0.11, 0.02]}
              rotation={[-Math.PI, 0.63, -Math.PI]}
              scale={[0.5, 0.6, 0.49]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pSphere1_lambert4_0.geometry}
                material={materials.lambert4}
              />
            </group>
          </group>
          <group position={[0, 0.88, -2.26]}>
            <group
              position={[0.96, -0.35, 0.97]}
              rotation={[0, 0.3, 0]}
              scale={[0.39, 0.27, 0.4]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pSphere1_lambert5_0.geometry}
                material={materials.lambert5}
              />
            </group>
          </group>
          <group
            position={[-0.45, 0.44, 0]}
            rotation={[-0.04, 0.07, -0.09]}
            scale={[0.06, 0.41, 0.06]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube2_lambert6_0.geometry}
              material={materials.lambert6}
            />
          </group>
          <group
            position={[-0.95, 0.81, -0.17]}
            rotation={[0, -0.24, 0]}
            scale={[-0.86, 1, 1]}
          >
            <group
              position={[-0.45, -0.44, 0]}
              rotation={[-0.04, 0.07, -0.09]}
              scale={[0.06, 0.41, 0.06]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pCube2_pasted__lambert6_0.geometry}
                material={materials.pasted__lambert6}
              />
            </group>
          </group>
          <group position={[-0.75, 0.73, 0.37]} rotation={[3.07, -1.12, 2.98]}>
            <group
              position={[-0.95, -0.07, -0.17]}
              rotation={[0, -0.24, 0]}
              scale={[-0.86, 1, 1]}
            >
              <group
                position={[-0.46, -0.44, 0]}
                rotation={[-0.04, 0.07, -0.09]}
                scale={[0.06, 0.41, 0.06]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pCube2_pasted__pasted__lambert6_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert6}
                />
              </group>
            </group>
          </group>
          <group position={[2.43, 0.88, -1.77]} rotation={[0, 0.63, 0]}>
            <group
              position={[-0.53, -0.51, -0.06]}
              rotation={[-0.04, 0.07, -0.09]}
              scale={[0.06, 0.41, 0.06]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pCube2_pasted__lambert7_0.geometry}
                material={materials.pasted__lambert7}
              />
            </group>
            <group
              position={[-0.95, -0.07, -0.17]}
              rotation={[0, -0.24, 0]}
              scale={[-0.86, 1, 1]}
            >
              <group
                position={[-0.35, -0.51, -0.04]}
                rotation={[-0.04, 0.07, -0.09]}
                scale={[0.06, 0.41, 0.06]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pCube2_pasted__pasted__lambert7_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert7}
                />
              </group>
            </group>
            <group
              position={[-0.75, -0.16, 0.37]}
              rotation={[3.07, -1.12, 2.98]}
            >
              <group
                position={[-0.95, -0.07, -0.17]}
                rotation={[0, -0.24, 0]}
                scale={[-0.86, 1, 1]}
              >
                <group
                  position={[-0.47, -0.5, 0.1]}
                  rotation={[-0.04, 0.07, -0.09]}
                  scale={[0.06, 0.41, 0.06]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pCube2_pasted__pasted__pasted__lambert6_0
                        .geometry
                    }
                    material={materials.pasted__pasted__pasted__lambert6}
                  />
                </group>
              </group>
            </group>
          </group>
          <group position={[-2.09, 0.79, 0]}>
            <group position={[2.43, 0, -1.77]} rotation={[0, 0.63, 0]}>
              <group
                position={[-0.45, -0.51, 0]}
                rotation={[0.27, 0.04, -0.11]}
                scale={[0.06, 0.41, 0.06]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pCube2_pasted__pasted__lambert8_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert8}
                />
              </group>
              <group
                position={[-0.95, -0.07, -0.17]}
                rotation={[0, -0.24, 0]}
                scale={[-0.86, 1, 1]}
              >
                <group
                  position={[-0.46, -0.46, 0]}
                  rotation={[0.27, 0.04, -0.11]}
                  scale={[0.06, 0.41, 0.06]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pCube2_pasted__pasted__pasted__lambert7_0
                        .geometry
                    }
                    material={materials.pasted__pasted__pasted__lambert7}
                  />
                </group>
              </group>
              <group
                position={[-0.75, -0.16, 0.37]}
                rotation={[3.07, -1.12, 2.98]}
              >
                <group
                  position={[-0.95, -0.07, -0.17]}
                  rotation={[0, -0.24, 0]}
                  scale={[-0.86, 1, 1]}
                >
                  <group
                    position={[-0.46, -0.41, 0]}
                    rotation={[0.02, 0.07, -0.09]}
                    scale={[0.06, 0.41, 0.06]}
                  >
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={
                        nodes
                          .pasted__pasted__pasted__pasted__pCube2_pasted__pasted__pasted__pasted__lambert6_0
                          .geometry
                      }
                      material={
                        materials.pasted__pasted__pasted__pasted__lambert6
                      }
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[0, 0.88, 0]}>
            <group
              position={[0.83, -0.61, -1.79]}
              rotation={[-0.14, 0, 0]}
              scale={[0.07, 0.08, 0.08]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.pasted__pCube3_pasted__lambert8_0.geometry}
                material={materials.pasted__lambert8}
              />
            </group>
          </group>
          <group position={[-0.14, 0.83, 1.24]} rotation={[0.05, 0.51, -0.03]}>
            <group
              position={[0.83, -0.62, -2.15]}
              rotation={[-0.14, 0, 0]}
              scale={[0.07, 0.08, 0.08]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.pasted__pasted__pCube3_pasted__pasted__lambert9_0
                    .geometry
                }
                material={materials.pasted__pasted__lambert9}
              />
            </group>
          </group>
          <group position={[1.25, 0.76, -0.45]} rotation={[0.06, -0.84, -0.08]}>
            <group
              position={[-0.14, -0.06, 1.24]}
              rotation={[0.05, 0.51, -0.03]}
            >
              <group
                position={[0.84, -0.59, -2.14]}
                rotation={[-0.14, 0, 0]}
                scale={[0.07, 0.08, 0.08]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes
                      .pasted__pasted__pasted__pCube3_pasted__pasted__pasted__lambert9_0
                      .geometry
                  }
                  material={materials.pasted__pasted__pasted__lambert9}
                />
              </group>
            </group>
          </group>
          <group
            position={[-1.74, 0.48, -1.42]}
            rotation={[-Math.PI, -1.44, -2.9]}
          >
            <group
              position={[1.25, -0.12, -0.45]}
              rotation={[0.06, -0.84, -0.08]}
            >
              <group
                position={[-0.14, -0.06, 1.24]}
                rotation={[0.05, 0.51, -0.03]}
              >
                <group
                  position={[0.82, -0.64, -2.13]}
                  rotation={[-0.14, 0, 0]}
                  scale={[0.07, 0.08, 0.08]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pasted__pCube3_pasted__pasted__pasted__pasted__lambert9_0
                        .geometry
                    }
                    material={
                      materials.pasted__pasted__pasted__pasted__lambert9
                    }
                  />
                </group>
              </group>
            </group>
          </group>
          <group position={[-0.22, 0.98, -0.16]} rotation={[0.19, -1.35, 0]}>
            <group
              position={[0.84, -0.62, -2.15]}
              rotation={[-0.14, 0, 0]}
              scale={[0.07, 0.08, 0.08]}
            >
              <mesh
                castShadow
                receiveShadow
                geometry={
                  nodes.pasted__pasted__pCube3_pasted__pasted__lambert10_0
                    .geometry
                }
                material={materials.pasted__pasted__lambert10}
              />
            </group>
          </group>
          <group
            position={[2.9, 0.8, -0.98]}
            rotation={[-Math.PI, -0.05, -Math.PI]}
          >
            <group position={[2.43, 0, -1.77]} rotation={[0, 0.63, 0]}>
              <group
                position={[-0.45, -0.44, 0]}
                rotation={[-0.04, 0.07, -0.09]}
                scale={[0.06, 0.41, 0.06]}
              >
                <mesh
                  castShadow
                  receiveShadow
                  geometry={
                    nodes.pasted__pasted__pCube2_pasted__pasted__lambert11_0
                      .geometry
                  }
                  material={materials.pasted__pasted__lambert11}
                />
              </group>
              <group
                position={[-0.95, -0.07, -0.17]}
                rotation={[0, -0.24, 0]}
                scale={[-0.86, 1, 1]}
              >
                <group
                  position={[-0.45, -0.44, 0]}
                  rotation={[-0.04, 0.07, -0.09]}
                  scale={[0.06, 0.41, 0.06]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pCube2_pasted__pasted__pasted__lambert10_0
                        .geometry
                    }
                    material={materials.pasted__pasted__pasted__lambert10}
                  />
                </group>
              </group>
              <group
                position={[-0.75, -0.16, 0.37]}
                rotation={[3.07, -1.12, 2.98]}
              >
                <group
                  position={[-0.95, -0.07, -0.17]}
                  rotation={[0, -0.24, 0]}
                  scale={[-0.86, 1, 1]}
                >
                  <group
                    position={[-0.46, -0.44, 0]}
                    rotation={[-0.04, 0.07, -0.09]}
                    scale={[0.06, 0.41, 0.06]}
                  >
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={
                        nodes
                          .pasted__pasted__pasted__pasted__pCube2_pasted__pasted__pasted__pasted__lambert10_0
                          .geometry
                      }
                      material={
                        materials.pasted__pasted__pasted__pasted__lambert10
                      }
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[3.91, 0.94, 0.73]} rotation={[0, 1.56, 0]}>
            <group position={[-2.09, -0.09, 0]}>
              <group position={[2.43, 0, -1.77]} rotation={[0, 0.63, 0]}>
                <group
                  position={[0.11, -0.51, 0.01]}
                  rotation={[0.27, 0.04, -0.11]}
                  scale={[0.06, 0.41, 0.06]}
                >
                  <mesh
                    castShadow
                    receiveShadow
                    geometry={
                      nodes
                        .pasted__pasted__pasted__pCube2_pasted__pasted__pasted__lambert8_0
                        .geometry
                    }
                    material={materials.pasted__pasted__pasted__lambert8}
                  />
                </group>
                <group
                  position={[-0.95, -0.07, -0.17]}
                  rotation={[0, -0.24, 0]}
                  scale={[-0.86, 1, 1]}
                >
                  <group
                    position={[-1.1, -0.46, -0.13]}
                    rotation={[0.27, 0.04, -0.11]}
                    scale={[0.06, 0.41, 0.06]}
                  >
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={
                        nodes
                          .pasted__pasted__pasted__pasted__pCube2_pasted__pasted__pasted__pasted__lambert7_0
                          .geometry
                      }
                      material={
                        materials.pasted__pasted__pasted__pasted__lambert7
                      }
                    />
                  </group>
                </group>
                <group
                  position={[-0.75, -0.16, 0.37]}
                  rotation={[3.07, -1.12, 2.98]}
                >
                  <group
                    position={[-0.95, -0.07, -0.17]}
                    rotation={[0, -0.24, 0]}
                    scale={[-0.86, 1, 1]}
                  >
                    <group
                      position={[-0.05, -0.45, -0.44]}
                      rotation={[0.02, 0.07, -0.09]}
                      scale={[0.06, 0.41, 0.06]}
                    >
                      <mesh
                        castShadow
                        receiveShadow
                        geometry={
                          nodes
                            .pasted__pasted__pasted__pasted__pasted__pCube2_pasted__pasted__pasted__pasted__pasted__lambert6_0
                            .geometry
                        }
                        material={
                          materials.pasted__pasted__pasted__pasted__pasted__lambert6
                        }
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
          <group position={[-0.09, 0.97, -1.29]} rotation={[0.24, 1.31, -0.11]}>
            <group
              position={[-1.74, -0.4, -1.42]}
              rotation={[-Math.PI, -1.44, -2.9]}
            >
              <group
                position={[1.25, -0.12, -0.45]}
                rotation={[0.06, -0.84, -0.08]}
              >
                <group
                  position={[-0.14, -0.06, 1.24]}
                  rotation={[0.05, 0.51, -0.03]}
                >
                  <group
                    position={[0.7, -0.64, -2.28]}
                    rotation={[-0.14, 0, 0]}
                    scale={[0.07, 0.08, 0.08]}
                  >
                    <mesh
                      castShadow
                      receiveShadow
                      geometry={
                        nodes
                          .pasted__pasted__pasted__pasted__pasted__pCube3_pasted__pasted__pasted__pasted__pasted__lambert9_0
                          .geometry
                      }
                      material={
                        materials.pasted__pasted__pasted__pasted__pasted__lambert9
                      }
                    />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

function Leaf({ group, props, nodes, materials }: IGroupProps) {
  return (
    <group ref={group} dispose={null}>
      <mesh
        name="ground"
        position={props.position}
        scale={undefined}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <boxBufferGeometry attach="geometry" args={[4.75, 4.75, 0.2]} />
        <meshStandardMaterial attach="material" color="white" />
      </mesh>
      <group
        {...props}
        position={[
          props.position[0],
          props.position[1] + 1.1,
          props.position[2],
        ]}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[-0.46, -0.16, -0.05]} rotation={[0.31, 1.17, 0.49]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pPlane1_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group rotation={[0.62, 0.24, 0.32]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__pPlane1_lambert1_0.geometry}
              material={materials.lambert1}
            />
          </group>
          <group
            position={[-0.01, -0.05, 0.24]}
            rotation={[0.88, 0.31, 0.52]}
            scale={[1, 1, 0.68]}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pasted__pPlane1_lambert1_0_1.geometry}
              material={materials.lambert1}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

function PineTree({ group, props, nodes, materials }: IGroupProps) {
  return (
    <group ref={group} dispose={null}>
      <mesh
        name="ground"
        position={props.position}
        scale={undefined}
        rotation={[-Math.PI / 2, 0, 0]}
      >
        <boxBufferGeometry attach="geometry" args={[4.75, 4.75, 0.2]} />
        <meshStandardMaterial attach="material" color="white" />
      </mesh>
      <group {...props} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 0.66, 0]}>
            <mesh
              castShadow
              receiveShadow
              geometry={
                nodes.group3_pasted__group1_pasted__pasted__pCone1_lambert1_0
                  .geometry
              }
              material={materials.lambert1}
            />
          </group>
          <group position={[-0.7, 0.06, 0.11]} scale={6.76}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pPlane1_lambert2_0.geometry}
              material={materials.lambert2}
            />
          </group>
          <group position={[-0.84, 0.37, 0.18]} scale={0.7}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.pCube3_lambert3_0.geometry}
              material={materials.lambert3}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

export default function Model({ treeSource, ...props }: DynamicTreeProps) {
  const group = useRef<Group>(null);
  const { nodes, materials } = useGLTF(
    `/models/${treeSource}/scene.glb`
  ) as any;
  props.scale = SCALE_BASE_MAPPED[treeSource];
  const mainProps = { group: group, nodes: nodes, materials: materials };
  switch (treeSource) {
    case "pine_tree":
      return <PineTree {...mainProps} props={props} />;
    case "leaf":
      return <Leaf {...mainProps} props={props} />;
    case "pumpkin":
      return <Pumpkin {...mainProps} props={props} />;
    case "mushroom":
      return <Mushroom {...mainProps} props={props} />;
    case "birch_tree":
      return <BirchTree {...mainProps} props={props} />;
    case "god_tree":
      return <GodTree {...mainProps} props={props} />;
    default:
      return null;
  }
}

["pine_tree", "leaf", "pumpkin", "mushroom", "birch_tree", "god_tree"].map(
  (treeSource) => useGLTF.preload(`/models/${treeSource}/scene.glb`)
);
